# This is a known good minimal helm values file
# It is NOT SECURE
# name your datacenter
global:
  name: consul
  datacenter: dc1
server:
  replicas: 1
ui:
  enabled: true
connectInject:
  enabled: true
controller:
  enabled: true
